### ISSUE TITLE
Experience Kind: Volunteer

### ISSUE THREAD

**Issue by shenoa** [FizbuzHQ/fizbuz#10]
**Is your feature request related to a problem? Please describe.**
I believe volunteer experience is relevant, and should be marked as it's own type in that section.

**Describe the solution you'd like**
Option to select "Volunteer" from a drop down list when adding a new type of Experience to a profile. IE: "Volunteer - Cascadia JS 2013"

**Comment by crtr0** [comment]
You've got it!

Closed as fixed.
