### ISSUE TITLE
Unable to add Docker as skill.

### ISSUE THREAD

**Issue by duckinator** [FizbuzHQ/fizbuz#11]
**Describe the bug**

When I go to add "Docker" as a skill, it shows the little dialog saying `Create "Docker"`. However, when I try to do so, it says:

> Value passed for name not unique in DB: Docker

**To Reproduce**

1. Go to https://fizbuz.com/home/skills
2. Scroll to "Add Another Skill"
3. In the "Add A Skill" textbox, enter "Docker"
4. Note the only option is "Create Docker". Choose that option.
5. Set "Kind" to "Software"
6. Set "Name" to "Docker"
7. Set "Description" to `Docker provides a way to run applications isolated in a container, packaged with all its dependencies and libraries.`
8. Set URL to "https://www.docker.com"
9. Click "Insert Tool"
10. See error: `Value passed for name not unique in DB: Docker`

NOTE: Technically, steps 7 and 8 aren't required. However, I included them in case someone tries reproducing it and it actually works.

**Expected behavior**

Either there would be an option _besides_ "Create Docker", or creating it would work.

**Screenshots**

![Screenshot_20190531_081332](https://user-images.githubusercontent.com/39698/58705080-14d1fc00-837c-11e9-91ae-08d02e39b93a.png)

![Screenshot_20190531_081405](https://user-images.githubusercontent.com/39698/58705081-17345600-837c-11e9-809b-b4c60ea5690d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser: Firefox 66.0.2

**Additional context**

I was able to successfully add other skills (e.g. CherryPy).

**Comment by crtr0** [comment]
Sorry you ran into that bug, thank you for reporting. 🙏

I've shipped a fix and you should now see Docker when you search to "Add a Skill".

**Comment by crtr0** [comment]
Closing as "fixed".

**Comment by duckinator** [comment]
Confirmed, works now. :+1:
