### ISSUE TITLE
Ability to specify preference for full-time vs part-time and long-term vs short-term work

### ISSUE THREAD

**Issue by duckinator** [FizbuzHQ/fizbuz#12]
**Is your feature request related to a problem? Please describe.**

I am looking for work, but specifically am looking for part-time work to supplement the part-time job I currently have. It would be nice to be able to specify that.

It would also be nice to be able to specify whether I'm looking for long-term work, short-term work, or either.

**Describe the solution you'd like**

- Full-time vs part-time: the option to choose between looking for [full-time, part-time, either].
- Long-term vs short-term: the option to choose between looking for [short-term, long-term, either].

**Comment by crtr0** [comment]
Thanks for the feedback, I've added your suggestions. 

Closed as fixed.
