### ISSUE TITLE
Profile missing icons next to codepen/volunteeer experience

### ISSUE THREAD

**Issue by kellim** [FizbuzHQ/fizbuz#14]
**Describe the bug**
There are no icons in profile next to your Codepen link or next to volunteer experience.

**To Reproduce**
1. Go to https://fizbuz.com/home when logged in
2. Click on View Profile button
3. Look at Codepen link (if one was added to External Links) and volunteer links (if any were added to Experiences) and notice there are no icons next to them.

**Expected behavior**
Icons should appear next to your Codepen link and any volunteer links so the items look uniform with other items in that section.

**Screenshots**
Red boxes have been added around the areas with the issue.
![fizbuz-bug-missing-icons](https://user-images.githubusercontent.com/2024584/58741851-4d50f480-83d3-11e9-8af7-766112ac2c96.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
There's no SVG in the page source next to the items missing an icon, so it doesn't seem to be an issue with an image not showing up in the browser.

**Comment by crtr0** [comment]
Thank you for flagging! Both issues have been resolved :)

Closed as fixed.
