### ISSUE TITLE
Typo in "Hires and invest in junior devs"

### ISSUE THREAD

**Issue by kempermr** [FizbuzHQ/fizbuz#16]
**Is your feature request related to a problem? Please describe.**
Missing "s" - Hires and invest**s** in junior devs

**Describe the solution you'd like**
Add an "s" to "invest"

**Comment by crtr0** [comment]
Closed as fixed.
<img width="255" alt="Screenshot 2019-06-01 09 08 07" src="https://user-images.githubusercontent.com/118628/58750919-de17e680-844c-11e9-97d8-1df06a7f23e3.png">
