### ISSUE TITLE
Markdown Task List

### ISSUE THREAD

**Issue by shenoa** [FizbuzHQ/fizbuz#9]
**Describe the bug**
Entering Markdown Task List translates as Unordered List

**To Reproduce**
1. Dashboard...Core...Edit...
2. Enter in About area multiline markdown for Task List items
3. Save with Update Account
4. View results with Dashboard....View Profile

**Expected behavior**
Should result in an intended item list with hanging line wrapping as per Github's extended syntax for Task Lists

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by crtr0** [comment]
Although we link to Github's Markdown docs page, we don't actually support all of their syntax. 

I've gone ahead and updated the link to reduce confusion on this. Thanks for flagging.

Closed as fixed.
